# Generated by Django 4.1.7 on 2023-03-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagem",
            options={"verbose_name": "Imagem", "verbose_name_plural": "Imagens"},
        ),
        migrations.AlterModelOptions(
            name="visitas",
            options={"verbose_name": "Visita", "verbose_name_plural": "Visitas"},
        ),
    ]
